version: '2'
services:
  estored:
    build: .
    image: gprevost/estored:latest
    ports:
     - $ESTORED_PORT:8080
     - $ESTORED_SSL_PORT:8443
    env_file: .env
    depends_on:
     - makecerts
     - mysql-server
     - rabbitmq-server
    networks:
      - estored
    volumes:
     - ./certs:/certs:ro
     
  mysql-server:
    image: mysql:latest
    ports: 
      - $MYSQL_PORT:3306
    env_file: .env
    networks:
      - estored

  rabbitmq-server:
    build: rabbitmq-ssl
    image: gprevost/rabbitmq-ssl:latest
    ports:
      - $RABBITMQ_BROKER_PORT:5671
      - $RABBITMQ_BROKER_STOMP_PORT:15671
      - $RABBITMQ_BROKER_MANAGEMENT_PORT:15672
    env_file: .env
    networks:
      - estored

  makecerts:
    build: makecerts
    image: gprevost/makecerts:latest
    volumes:
        - ./certs:/opt/certs
    command:
        "/run.sh"
    networks:
      - estored

  estored-examples-datasource:
    build: estored-examples-datasource
    image: gprevost/estored-examples-datasource:latest
    env_file: .env
    depends_on:
     - rabbitmq-server
    networks:
      - estored
    volumes:
     - ./certs:/certs:ro
     - ./estored-examples-datasource/datafiles:/datafiles:ro
     
  estored-mytardis-datasource:
    build: estored-mytardis-datasource
    image: gprevost/estored-mytardis-datasource:latest
    env_file: .env
    depends_on:
     - rabbitmq-server
    networks:
      - estored
    volumes:
     - ./certs:/certs:ro
    
networks:
  estored:
    driver: bridge
