version: '2'

services:

  estored:
    build: .
    image: gprevost/estored:latest
    ports:
     - $ESTORED_PORT:8080
     - $ESTORED_SSL_PORT:8443
    env_file: .env
    depends_on:
     - makecerts
     - mysql
     - rabbitmq
    networks:
      - estored
    volumes:
     - ./certs:/certs:ro
     
  mysql:
    image: mysql:5.7
    ports: 
      - $MYSQL_PORT:3306
    environment:
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    volumes:
     - ./mysql/init:/docker-entrypoint-initdb.d 
    networks:
      - estored

  rabbitmq:
    build: rabbitmq-ssl
    image: gprevost/rabbitmq-ssl:latest
    ports:
      - $RABBITMQ_BROKER_PORT:5671
      - $RABBITMQ_BROKER_STOMP_PORT:15671
      - $RABBITMQ_BROKER_MANAGEMENT_PORT:15672
    env_file: .env
    volumes:
      - ./rabbitmq-ssl/config:/etc/rabbitmq
    networks:
      - estored

  makecerts:
    build: makecerts
    image: gprevost/makecerts:latest
    command:
        "/run.sh"
    volumes:
        - ./certs:/opt/certs
    networks:
      - estored

  ds-examples:
    build: estored-examples-datasource
    image: gprevost/estored-examples-datasource:latest
    env_file: .env
    depends_on:
     - rabbitmq
    volumes:
     - ./certs:/certs:ro
     - ./estored-examples-datasource/datafiles:/datafiles:ro
    networks:
      - estored

  ds-mytardis:
    build: estored-mytardis-datasource
    image: gprevost/estored-mytardis-datasource:latest
    env_file: .env
    depends_on:
     - rabbitmq
    volumes:
     - ./certs:/certs:ro
    networks:
      - estored


networks:
  estored:
    driver: bridge
